### ISSUE TITLE
Crash on Fabric

### ISSUE THREAD

**Issue by BigPhobos** [dayofpi/mob-catalog#3]
Minecraft 1.20.1
Fabric 0.15.3
Mob Catalog 1.0.7
https://gist.github.com/LunarPhobos/00189e13f8e51819f0dc85e2ceb4098a

**Comment by dayofpi** [comment]
Sorry for the inconvenience. Is the issue resolved if you install this library? https://modrinth.com/mod/forge-config-api-port

**Comment by BigPhobos** [comment]
Yes, this resolves the issue. Thank you.
