### ISSUE TITLE
[Crash] Sloth Entity - Aged Modpack - Possibly Mob Catalog

### ISSUE THREAD

**Issue by xR4YM0ND** [dayofpi/mob-catalog#5]
Hi, idk if this is a bug / crash with Mob Catalog or another mod in the [Aged modpack](about:blank).

A player reported a crash and it seems like your mod.
Could you take a look at it pls.

https://github.com/xR4YM0ND/Aged/issues/41

**Comment by cyyynthia** [comment]
Hi, after a painful day of troubleshooting on my own server I come here to confirm this is an issue from this mod as I'm experiencing it as well.

It appears the root-cause is the mod getting a blockstate from a worker thread without checking first if the block is from a loaded chunk. Fetching blockstates from loaded chunks should (?) be thread-safe, but if the chunk is unloaded this causes the thread to get loaded which is **not** a thread safe operation.
